
# -*- coding: utf-8 -*-
"""Download_BLIP2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13BIPdHYYD4AxoMKJ5aNj5qggWDuKeBc6
"""

from huggingface_hub import snapshot_download
from transformers import Blip2ForConditionalGeneration, AutoProcessor
import torch
import requests
from PIL import Image

if __name__ == "__main__":
    # Download the model
    repo_id = "Salesforce/blip2-opt-2.7b"
    local_dir = "/home/aa/文档/AttieLin/models/BLIP2"
    snapshot_download(repo_id=repo_id, local_dir=local_dir)

    # import shutil
    # shutil.make_archive('./BLIP2', 'zip', './models/BLIP2/')

